[workspace]
members = [
    "plugin"
]

[profile.release]
debug = true
lto = true
codegen-units = 1

[workspace.dependencies]
solana-geyser-plugin-interface = "=1.17.25"
solana-sdk = "=1.17.25"
solana-streamer = "=1.17.25"
solana-quic-client = "=1.17.25"
solana-net-utils = "=1.17.25"
solana-connection-cache = "=1.17.25"
